---
name: Feature request
about: Suggest an idea for this project
title: "Feature Request: "
labels: ["enhancement", "copilot"]
assignees: ["copilot"] # <-- TUNE ME
---

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Additional context**
Add any other context or screenshots about the feature request here.